// Vaccine record PDF export/share [live-requested: "we should be able to
// export or share the vax to a PDF with the nice header and details"] —
// builds a printable HTML immunization record (grouped Person → Vaccine →
// Dose, same structure the in-app list now uses) and hands it to
// expo-print/expo-sharing. No new backend involved; runs entirely
// client-side against whatever vaccine records are currently loaded.
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Vaccine } from './types';
import { fmtDate } from '@/lib/dates';

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

interface VaxPdfMember {
  memberId: string;
  memberName: string;
  vaccines: Vaccine[];
}

export async function shareVaccineRecordsPdf(params: {
  familyName: string;
  members: VaxPdfMember[];
}) {
  const { familyName, members } = params;
  const generatedAt = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  const memberSections = members.map(m => {
    // Group this member's own doses by vaccine name, newest dose first —
    // mirrors the in-app grouped list exactly.
    const byName = new Map<string, Vaccine[]>();
    for (const v of m.vaccines) {
      const list = byName.get(v.title) ?? [];
      list.push(v);
      byName.set(v.title, list);
    }
    const vaccineBlocks = Array.from(byName.entries()).map(([title, doses]) => {
      const sorted = doses.slice().sort((a, b) => b.date.localeCompare(a.date));
      const rows = sorted.map(v => `
        <tr>
          <td>${escapeHtml(fmtDate(v.date))}</td>
          <td>${v.series_total > 1 ? `Dose ${v.series_current} of ${v.series_total}` : '—'}</td>
          <td>${v.done ? 'Completed' : 'Scheduled'}</td>
          <td>${escapeHtml(v.administered_by ?? '—')}</td>
          <td>${escapeHtml(v.location ?? '—')}</td>
          <td>${v.next_due_date ? escapeHtml(fmtDate(v.next_due_date)) : '—'}</td>
        </tr>
      `).join('');
      return `
        <div class="vaccine-block">
          <h3>${escapeHtml(title)}${sorted[0]?.vaccine_type ? ` <span class="type">(${escapeHtml(sorted[0].vaccine_type!.toUpperCase())})</span>` : ''}</h3>
          <table>
            <thead>
              <tr><th>Date</th><th>Dose</th><th>Status</th><th>Administered By</th><th>Location</th><th>Next Due</th></tr>
            </thead>
            <tbody>${rows}</tbody>
          </table>
        </div>
      `;
    }).join('');

    return `
      <section class="member-section">
        <h2>${escapeHtml(m.memberName)}</h2>
        ${vaccineBlocks || '<p class="empty">No vaccine records on file.</p>'}
      </section>
    `;
  }).join('<div class="page-break"></div>');

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #2C2722; padding: 32px; }
          .header { border-bottom: 3px solid #3D7A5A; padding-bottom: 16px; margin-bottom: 24px; }
          .header h1 { font-size: 24px; margin: 0 0 4px; color: #2C2722; }
          .header .subtitle { font-size: 13px; color: #6B5F52; margin: 0; }
          .member-section { margin-bottom: 28px; }
          .member-section h2 { font-size: 18px; color: #3D7A5A; border-bottom: 1px solid #E1EFE7; padding-bottom: 6px; margin-bottom: 12px; }
          .vaccine-block { margin-bottom: 16px; }
          .vaccine-block h3 { font-size: 14px; margin: 0 0 6px; color: #2C2722; }
          .vaccine-block .type { font-size: 11px; color: #3D7A5A; font-weight: normal; }
          table { width: 100%; border-collapse: collapse; font-size: 11px; }
          th { text-align: left; background: #F2ECE1; padding: 6px 8px; color: #6B5F52; font-weight: 700; }
          td { padding: 6px 8px; border-bottom: 1px solid #F2ECE1; }
          .empty { font-size: 12px; color: #A69A8A; font-style: italic; }
          .page-break { page-break-before: always; }
          .footer { margin-top: 32px; font-size: 10px; color: #A69A8A; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${escapeHtml(familyName)} — Immunization Record</h1>
          <p class="subtitle">Generated ${escapeHtml(generatedAt)}</p>
        </div>
        ${memberSections}
        <div class="footer">Generated by Family Cube</div>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Immunization Record' });
  } else {
    await Print.printAsync({ uri });
  }
}
