import { StyleSheet, Platform } from 'react-native';

export function makeStyles(_colors: any, _isDark: boolean) {
  return StyleSheet.create({
    header:       { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16,
                    paddingBottom: 12, borderBottomWidth: StyleSheet.hairlineWidth },
    backBtn:      { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
    headerTitle:  { fontSize: 16, fontWeight: '800' },
    headerSub:    { fontSize: 14, marginTop: 1 },
    label:        { fontSize: 14, fontWeight: '700', letterSpacing: 0.5, marginBottom: 8 },
    photoBox:     { height: 220, borderRadius: 16, borderWidth: 1.5, borderStyle: 'dashed',
                    alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
    photoPreview: { width: '100%', height: '100%' },
    photoRemove:  { position: 'absolute', top: 8, right: 8, width: 26, height: 26,
                    borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
    textArea:     { borderRadius: 14, borderWidth: 1, padding: 14, fontSize: 14, minHeight: 100 },
    scanBtn:      { borderRadius: 16, paddingVertical: 16, flexDirection: 'row',
                    alignItems: 'center', justifyContent: 'center', gap: 10 },
    scanBtnText:  { fontSize: 16, fontWeight: '800', color: '#fff' },
    resultCard:   { borderRadius: 20, borderWidth: 1, overflow: 'hidden' },
    urgencyBanner:{ flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16 },
    urgencyLabel: { fontSize: 14, fontWeight: '900', letterSpacing: 0.5 },
    sectionText:  { fontSize: 14, lineHeight: 21, paddingHorizontal: 16, paddingVertical: 12 },
    chatBtn:      { flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
                    gap: 8, marginHorizontal: 16, marginTop: 10, borderRadius: 14, paddingVertical: 12,
                    borderWidth: 1.5 },
    disclaimerBox:  { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginHorizontal: 16,
                      marginTop: 14, marginBottom: 14, padding: 12, borderRadius: 12, borderWidth: 1 },
    disclaimerText: { flex: 1, fontSize: 14, lineHeight: 17 },
    pastCard:          { borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, padding: 14, marginBottom: 10 },
    pastThumb:         { width: 52, height: 52, borderRadius: 10, backgroundColor: '#0001' },
    pastDotWrap:       { width: 52, height: 52, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    urgencyPill:       { borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
    pastExpandedPhoto: { width: '100%', height: 180, borderRadius: 12 },
    photoZoomBadge:    { position: 'absolute', bottom: 8, right: 8, flexDirection: 'row', alignItems: 'center',
                         gap: 4, backgroundColor: 'rgba(0,0,0,0.55)', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
    filterChip:        { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4, borderWidth: 1, marginLeft: 6 },
    lightboxBg:        { flex: 1, backgroundColor: 'rgba(0,0,0,0.92)', alignItems: 'center', justifyContent: 'center' },
    lightboxImg:       { width: '100%', height: '80%' },
    lightboxClose:     { position: 'absolute', top: Platform.OS === 'ios' ? 56 : 24, right: 20,
                         width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.15)',
                         alignItems: 'center', justifyContent: 'center' },
  });
}
