/**
 * @react-native-voice/voice ships only a legacy ReactPackage (no TurboModule
 * spec/codegen — confirmed via its package.json and VoicePackage.java), and
 * this app runs with newArchEnabled: true. Under the New Architecture,
 * NativeModules.Voice resolves to null unless React Native's own legacy-
 * module interop layer is turned on — this is a real, documented RN 0.81
 * feature flag (useTurboModuleInterop, off by default), not something any
 * manifest/permission change (see withAndroidSpeechQueries.js, a separate,
 * real but insufficient fix for this same live crash) can address.
 *
 * ReactNativeFeatureFlags.override(...) must run before loadReactNative(this)
 * in MainApplication.kt's onCreate() — there's no JS-side or app.config.js
 * knob for this, so this plugin injects it directly into the generated file,
 * same reasoning as every other plugins/with*.js in this repo (MainApplication.kt
 * is regenerated by every `expo prebuild --clean`).
 *
 * iOS is entirely unaffected — @react-native-voice/voice's iOS side has no
 * equivalent New Architecture interop gap (confirmed: iOS's voice/speech-to-
 * text already works, per this app's own CLAUDE.md constraint to never
 * disturb what's already working there), and this plugin only ever touches
 * android/app/src/main/java/.../MainApplication.kt.
 */
const { withMainApplication } = require('@expo/config-plugins');

const IMPORT_LINE = 'import com.facebook.react.internal.featureflags.ReactNativeFeatureFlags';
const DEFAULTS_IMPORT = 'import com.facebook.react.internal.featureflags.ReactNativeFeatureFlagsDefaults';
const SOLOADER_IMPORT = 'import com.facebook.soloader.SoLoader';
const SOMAPPING_IMPORT = 'import com.facebook.react.soloader.OpenSourceMergedSoMapping';
// ReactNativeFeatureFlagsCxxInterop is a JNI-backed object whose <clinit>
// loads a native lib via SoLoader — calling ReactNativeFeatureFlags.override
// before SoLoader.init() runs throws IllegalStateException("SoLoader.init()
// not yet called"), a real crash confirmed live on this emulator
// (java.lang.ExceptionInInitializerError at MainApplication.onCreate).
// loadReactNative(this) normally calls SoLoader.init() itself, but only
// AFTER this plugin's override needs to already be in effect — so SoLoader
// must be initialized explicitly, first, right here.
const OVERRIDE_BLOCK = `    SoLoader.init(this, OpenSourceMergedSoMapping)
    ReactNativeFeatureFlags.override(object : ReactNativeFeatureFlagsDefaults() {
      override fun useTurboModuleInterop(): Boolean = true
    })
`;

module.exports = function withAndroidTurboModuleInterop(config) {
  return withMainApplication(config, (config) => {
    let contents = config.modResults.contents;

    if (!contents.includes(IMPORT_LINE)) {
      contents = contents.replace(
        /(import com\.facebook\.react\.defaults\.DefaultReactNativeHost\n)/,
        `$1${IMPORT_LINE}\n${DEFAULTS_IMPORT}\n${SOLOADER_IMPORT}\n${SOMAPPING_IMPORT}\n`
      );
    }

    if (!contents.includes('useTurboModuleInterop')) {
      contents = contents.replace(
        /(\s*)(loadReactNative\(this\))/,
        `$1${OVERRIDE_BLOCK}$1$2`
      );
    }

    config.modResults.contents = contents;
    return config;
  });
};
