// Static breed lists per species — used for autocomplete in add-pet and edit screens.
// Keeping as a simple sorted array. Extend freely.

export const BREEDS: Record<string, string[]> = {
  dog: [
    'Affenpinscher','Afghan Hound','Airedale Terrier','Akita','Alaskan Malamute',
    'American Bulldog','American Cocker Spaniel','American Eskimo Dog',
    'American Pit Bull Terrier','American Staffordshire Terrier','Anatolian Shepherd',
    'Australian Cattle Dog','Australian Shepherd','Australian Terrier',
    'Basenji','Basset Hound','Beagle','Bearded Collie','Bedlington Terrier',
    'Belgian Malinois','Belgian Sheepdog','Belgian Tervuren','Bernese Mountain Dog',
    'Bichon Frise','Black and Tan Coonhound','Bloodhound','Border Collie',
    'Border Terrier','Borzoi','Boston Terrier','Boxer','Boykin Spaniel',
    'Brittany','Brussels Griffon','Bull Terrier','Bulldog','Bullmastiff',
    'Cairn Terrier','Cane Corso','Cardigan Welsh Corgi','Cavalier King Charles Spaniel',
    'Chesapeake Bay Retriever','Chihuahua','Chinese Crested','Chinese Shar-Pei',
    'Chow Chow','Clumber Spaniel','Cocker Spaniel','Collie','Curly-Coated Retriever',
    'Dachshund','Dalmatian','Doberman Pinscher','Dogo Argentino',
    'English Bulldog','English Cocker Spaniel','English Setter','English Springer Spaniel',
    'Field Spaniel','Finnish Spitz','Flat-Coated Retriever','French Bulldog',
    'German Pinscher','German Shepherd','German Shorthaired Pointer','German Wirehaired Pointer',
    'Giant Schnauzer','Golden Retriever','Gordon Setter','Great Dane','Great Pyrenees',
    'Greyhound','Havanese','Ibizan Hound','Irish Setter','Irish Terrier',
    'Irish Water Spaniel','Irish Wolfhound','Italian Greyhound','Jack Russell Terrier',
    'Japanese Chin','Keeshond','Kerry Blue Terrier','Komondor','Kuvasz',
    'Labrador Retriever','Lakeland Terrier','Leonberger','Lhasa Apso',
    'Maltese','Manchester Terrier','Mastiff','Miniature Pinscher','Miniature Schnauzer',
    'Mixed Breed','Newfoundland','Norfolk Terrier','Norwegian Elkhound',
    'Norwich Terrier','Old English Sheepdog','Otterhound','Papillon',
    'Pembroke Welsh Corgi','Petit Basset Griffon Vendeen','Pharaoh Hound',
    'Plott Hound','Pointer','Pomeranian','Poodle','Portuguese Water Dog',
    'Pug','Rat Terrier','Redbone Coonhound','Rhodesian Ridgeback','Rottweiler',
    'Saint Bernard','Saluki','Samoyed','Schipperke','Scottish Deerhound',
    'Scottish Terrier','Sealyham Terrier','Shetland Sheepdog','Shiba Inu',
    'Shih Tzu','Siberian Husky','Silky Terrier','Skye Terrier','Sloughi',
    'Soft Coated Wheaten Terrier','Spinone Italiano','Staffordshire Bull Terrier',
    'Standard Schnauzer','Sussex Spaniel','Tibetan Mastiff','Tibetan Spaniel',
    'Tibetan Terrier','Toy Fox Terrier','Treeing Walker Coonhound',
    'Vizsla','Weimaraner','Welsh Springer Spaniel','Welsh Terrier',
    'West Highland White Terrier','Whippet','Wirehaired Pointing Griffon',
    'Yorkshire Terrier',
  ],
  cat: [
    'Abyssinian','American Bobtail','American Curl','American Shorthair',
    'American Wirehair','Balinese','Bengal','Birman','Bombay','British Shorthair',
    'Burmese','Burmilla','California Spangled','Chartreux','Chausie',
    'Colorpoint Shorthair','Cornish Rex','Devon Rex','Domestic Longhair',
    'Domestic Medium Hair','Domestic Shorthair','Egyptian Mau','European Shorthair',
    'Exotic Shorthair','Havana Brown','Highlander','Himalayan','Japanese Bobtail',
    'Javanese','Khao Manee','Korat','LaPerm','Maine Coon','Manx',
    'Munchkin','Nebelung','Norwegian Forest Cat','Ocicat','Oriental',
    'Persian','Peterbald','Pixiebob','Ragamuffin','Ragdoll','Russian Blue',
    'Savannah','Scottish Fold','Selkirk Rex','Siamese','Siberian',
    'Singapura','Snowshoe','Sokoke','Somali','Sphynx','Thai',
    'Tonkinese','Toyger','Turkish Angora','Turkish Van',
  ],
  rabbit: [
    'American','American Chinchilla','American Fuzzy Lop','Angora (English)',
    'Angora (French)','Angora (Giant)','Angora (Satin)','Belgian Hare',
    'Beveren','Blanc de Hotot','Blue-Eyed White','Britannia Petite',
    'Californian','Champagne D\'Argent','Checkered Giant','Cinnamon',
    'Creme D\'Argent','Dutch','Dwarf Hotot','English Lop','English Spot',
    'Flemish Giant','Florida White','Giant Chinchilla','Harlequin',
    'Havana','Holland Lop','Jersey Wooly','Lilac','Lionhead',
    'Mini Lop','Mini Rex','Mini Satin','Netherland Dwarf','New Zealand',
    'Palomino','Polish','Rex','Rhinelander','Satin','Silver',
    'Silver Fox','Silver Marten','Standard Chinchilla','Tan',
    'Thrianta','Mixed Breed',
  ],
  bird: [
    'African Grey Parrot','Amazon Parrot','Budgerigar (Budgie)','Caique',
    'Canary','Citron-crested Cockatoo','Cockatiel','Cockatoo','Conure',
    'Diamond Dove','Eclectus Parrot','Finch','Galah Cockatoo',
    'Gouldian Finch','Green-cheeked Conure','Hyacinth Macaw',
    'Java Sparrow','Jenday Conure','Kakariki','Kookaburra','Lovebird',
    'Macaw','Meyer\'s Parrot','Monk Parakeet','Myna Bird','Pacific Parrotlet',
    'Parakeet','Parrotlet','Peach-faced Lovebird','Pionus Parrot',
    'Pied Cockatiel','Pigeon','Quaker Parrot','Rainbow Lorikeet',
    'Ringneck Parakeet','Rose-breasted Cockatoo','Scarlet Macaw',
    'Senegal Parrot','Sun Conure','Toucan','White-capped Pionus',
    'Yellow-naped Amazon','Zebra Finch','Mixed Breed',
  ],
  fish: [
    'Betta','Goldfish','Guppy','Platy','Molly','Swordtail','Tetra',
    'Angelfish','Discus','Oscar','Cichlid','Koi','Corydoras',
    'Plecostomus','Barb','Danio','Rasbora','Loach','Gouami',
    'Rainbow Fish','Clownfish','Tang','Wrasse','Damselfish','Mixed',
  ],
  hamster: [
    'Syrian (Golden) Hamster','Dwarf Campbell Russian','Dwarf Winter White Russian',
    'Roborovski Dwarf','Chinese Hamster','European Hamster','Mixed',
  ],
  turtle: [
    'Red-eared Slider','Box Turtle','Painted Turtle','Map Turtle',
    'Musk Turtle','Mud Turtle','Snapping Turtle','Russian Tortoise',
    'Hermann\'s Tortoise','Sulcata Tortoise','Greek Tortoise',
    'Leopard Tortoise','Indian Star Tortoise','Horsfield\'s Tortoise','Mixed',
  ],
  other: ['Mixed Breed / Unknown'],
};

/** Returns breeds for a species filtered by query (case-insensitive substring). */
export function filterBreeds(species: string, query: string): string[] {
  const list = BREEDS[species] ?? BREEDS.other;
  if (!query.trim()) return list.slice(0, 10);
  const q = query.toLowerCase();
  return list.filter(b => b.toLowerCase().includes(q)).slice(0, 8);
}
