export const DEFAULT_GROCERY_ITEMS = [
  // ── Fresh Produce: Fruits ────────────────────────────────────────────────
  'Apples', 'Bananas', 'Oranges', 'Grapes', 'Strawberries', 'Blueberries', 'Raspberries',
  'Blackberries', 'Lemons', 'Limes', 'Avocados', 'Mangoes', 'Papayas', 'Pineapple',
  'Watermelon', 'Cantaloupe', 'Honeydew', 'Pomegranate', 'Guava', 'Jackfruit', 'Lychee',
  'Dragon fruit', 'Passion fruit', 'Kiwi', 'Peaches', 'Plums', 'Pears', 'Cherries',
  'Nectarines', 'Apricots', 'Figs', 'Dates', 'Coconut', 'Starfruit', 'Rambutan',
  'Persimmon', 'Quince', 'Tamarind', 'Breadfruit', 'Sapota (chikoo)', 'Jamun',
  'Gooseberry (amla)', 'Bael fruit', 'Custard apple',

  // ── Fresh Produce: Vegetables ────────────────────────────────────────────
  'Tomatoes', 'Cherry tomatoes', 'Roma tomatoes', 'Heirloom tomatoes',
  'Lettuce', 'Romaine lettuce', 'Iceberg lettuce', 'Butter lettuce',
  'Spinach', 'Baby spinach', 'Kale', 'Swiss chard', 'Arugula', 'Collard greens',
  'Mustard greens', 'Methi (fenugreek leaves)', 'Broccoli', 'Cauliflower', 'Broccolini',
  'Carrots', 'Baby carrots', 'Celery', 'Cucumber', 'English cucumber', 'Persian cucumbers',
  'Bell peppers', 'Mini sweet peppers', 'Green chili', 'Red chili', 'Jalapeño',
  'Serrano pepper', 'Habanero', 'Poblano pepper', 'Anaheim pepper', 'Banana pepper',
  'Onions', 'Red onions', 'Spring onions', 'Shallots', 'Leek', 'Chives',
  'Garlic', 'Garlic bulbs', 'Elephant garlic',
  'Potatoes', 'Russet potatoes', 'Yukon gold potatoes', 'Red potatoes', 'Fingerling potatoes',
  'Sweet potatoes', 'Purple sweet potato', 'Taro root', 'Yam', 'Cassava', 'Lotus root',
  'Zucchini', 'Yellow squash', 'Butternut squash', 'Acorn squash', 'Spaghetti squash',
  'Pumpkin', 'Bitter gourd (karela)', 'Ridge gourd', 'Bottle gourd (lauki)', 'Snake gourd',
  'Drumstick (moringa)', 'Raw banana', 'Plantain', 'Eggplant', 'Japanese eggplant',
  'Indian eggplant', 'Okra (bhindi)', 'Beetroot', 'Radish', 'Daikon radish', 'Turnip',
  'Parsnip', 'Rutabaga', 'Kohlrabi', 'Fennel bulb', 'Artichoke', 'Brussels sprouts',
  'Baby corn', 'Corn', 'Bok choy', 'Napa cabbage', 'Savoy cabbage', 'Green cabbage',
  'Red cabbage', 'Bean sprouts', 'Bamboo shoots', 'Water chestnuts',
  'Asparagus', 'Green beans', 'Peas', 'Snow peas', 'Sugar snap peas', 'Edamame (fresh)',
  'Mushrooms', 'Button mushrooms', 'Portobello mushrooms', 'Shiitake mushrooms',
  'Oyster mushrooms', 'King oyster mushrooms', 'Enoki mushrooms', 'Cremini mushrooms',
  'Ginger', 'Galangal', 'Turmeric root', 'Horseradish',

  // ── Fresh Herbs ──────────────────────────────────────────────────────────
  'Cilantro', 'Mint', 'Curry leaves', 'Basil', 'Thai basil', 'Parsley', 'Dill',
  'Lemongrass', 'Kaffir lime leaves', 'Rosemary', 'Thyme', 'Oregano', 'Sage',
  'Tarragon', 'Chervil', 'Epazote', 'Pandan leaves',

  // ── Dairy & Eggs ─────────────────────────────────────────────────────────
  'Milk', 'Whole milk', '2% milk', 'Skim milk', 'Eggs', 'Free-range eggs',
  'Butter', 'Salted butter', 'Unsalted butter', 'Ghee', 'Clarified butter',
  'Cheddar cheese', 'Mild cheddar', 'Sharp cheddar', 'Mozzarella', 'Fresh mozzarella',
  'Parmesan', 'Parmigiano reggiano', 'Gouda', 'Brie', 'Camembert', 'Ricotta',
  'Feta cheese', 'Halloumi', 'Mascarpone', 'Gruyère', 'Swiss cheese', 'Provolone',
  'Paneer', 'Queso fresco', 'Queso blanco', 'Manchego',
  'Greek yogurt', 'Plain yogurt', 'Flavored yogurt', 'Skyr', 'Kefir',
  'Sour cream', 'Crème fraîche', 'Cream cheese', 'Heavy cream', 'Whipping cream',
  'Half and half', 'Buttermilk', 'Condensed milk', 'Evaporated milk',
  'Almond milk', 'Oat milk', 'Coconut milk (carton)', 'Soy milk', 'Cashew milk',
  'Rice milk', 'Pea milk', 'Cottage cheese', 'Labneh',

  // ── Meat & Poultry ───────────────────────────────────────────────────────
  'Chicken breast', 'Boneless chicken thighs', 'Whole chicken', 'Chicken wings',
  'Chicken drumsticks', 'Chicken tenders', 'Ground chicken',
  'Ground beef (80/20)', 'Ground beef (lean)', 'Beef steak', 'Ribeye steak',
  'Sirloin steak', 'Flank steak', 'Skirt steak', 'Beef short ribs', 'Beef brisket',
  'Beef chuck roast', 'Oxtail', 'Beef liver',
  'Lamb chops', 'Lamb leg', 'Lamb shoulder', 'Lamb mince', 'Mutton', 'Goat meat',
  'Pork chops', 'Pork belly', 'Pork shoulder', 'Pork tenderloin', 'Pork ribs',
  'Bacon', 'Pancetta', 'Prosciutto', 'Sausage', 'Italian sausage', 'Breakfast sausage',
  'Chorizo', 'Andouille sausage', 'Kielbasa', 'Salami', 'Pepperoni',
  'Turkey breast', 'Turkey mince', 'Deli ham', 'Deli turkey', 'Hot dogs', 'Vienna sausages',
  'Duck breast', 'Quail',

  // ── Seafood ──────────────────────────────────────────────────────────────
  'Salmon', 'Atlantic salmon', 'Sockeye salmon', 'Salmon fillet',
  'Shrimp', 'Prawns', 'Tiger prawns', 'King prawns',
  'Tuna (fresh)', 'Tuna (canned)', 'Sardines', 'Tilapia', 'Catfish',
  'Mackerel', 'Cod', 'Halibut', 'Sea bass', 'Snapper', 'Grouper', 'Flounder',
  'Trout', 'Mahi-mahi', 'Swordfish', 'Anchovies',
  'Crab', 'Blue crab', 'Dungeness crab', 'Snow crab legs',
  'Lobster', 'Lobster tails', 'Squid', 'Octopus', 'Clams', 'Mussels', 'Oysters', 'Scallops',

  // ── Bread & Bakery ───────────────────────────────────────────────────────
  'White bread', 'Whole wheat bread', 'Multigrain bread', 'Sourdough bread',
  'Rye bread', 'Pumpernickel', 'Brioche', 'Baguette', 'Ciabatta',
  'Bagels', 'Everything bagels', 'English muffins', 'Croissants', 'Dinner rolls',
  'Flour tortillas', 'Corn tortillas', 'Pita bread', 'Lavash',
  'Naan', 'Garlic naan', 'Roti', 'Paratha', 'Puri', 'Bhatura',
  'Idli batter', 'Dosa batter',

  // ── Rice & Grains ────────────────────────────────────────────────────────
  'Basmati rice', 'Jasmine rice', 'Sona masoori rice', 'Brown basmati', 'Brown rice',
  'White rice', 'Parboiled rice', 'Sticky rice', 'Glutinous rice', 'Arborio rice',
  'Wild rice', 'Black rice', 'Red rice',
  'Pasta', 'Spaghetti', 'Penne', 'Fettuccine', 'Rigatoni', 'Farfalle', 'Fusilli',
  'Lasagne sheets', 'Macaroni', 'Angel hair', 'Orzo', 'Gnocchi',
  'Rice noodles', 'Egg noodles', 'Ramen noodles', 'Udon noodles', 'Soba noodles',
  'Vermicelli', 'Glass noodles', 'Lo mein noodles', 'Shirataki noodles',
  'Quinoa', 'Rolled oats', 'Steel-cut oats', 'Instant oats', 'Semolina (rava)',
  'Cream of wheat (upma rava)', 'Cornmeal', 'Grits',
  'Poha (flattened rice)', 'Millet (bajra)', 'Sorghum (jowar)', 'Ragi (finger millet)',
  'Barley', 'Bulgur wheat', 'Couscous', 'Farro', 'Freekeh', 'Teff', 'Amaranth',
  'Bread crumbs', 'Panko', 'Corn flakes', 'Granola',

  // ── Flour & Baking ───────────────────────────────────────────────────────
  'All-purpose flour', 'Whole wheat flour', 'Bread flour', 'Cake flour', 'Self-rising flour',
  'Besan (chickpea flour)', 'Rice flour', 'Corn flour', 'Cornstarch', 'Tapioca starch',
  'Almond flour', 'Oat flour', 'Coconut flour', 'Arrowroot powder',
  'Baking soda', 'Baking powder', 'Yeast (active dry)', 'Instant yeast',
  'Sugar', 'Brown sugar', 'Powdered sugar', 'Caster sugar', 'Coconut sugar',
  'Jaggery', 'Honey', 'Maple syrup', 'Agave nectar', 'Molasses',
  'Vanilla extract', 'Vanilla bean paste', 'Almond extract',
  'Chocolate chips', 'Dark chocolate', 'Cocoa powder', 'Unsweetened chocolate',
  'Bittersweet chocolate', 'White chocolate chips',

  // ── Lentils & Legumes ────────────────────────────────────────────────────
  'Toor dal', 'Moong dal (yellow)', 'Moong dal (green)', 'Masoor dal (red lentils)',
  'Urad dal', 'Urad dal (whole)', 'Chana dal', 'Rajma (kidney beans)', 'Chole (chickpeas)',
  'Black-eyed peas', 'Black beans', 'Navy beans', 'Great northern beans', 'Pinto beans',
  'Cannellini beans', 'Lima beans', 'Butter beans', 'Lentils (green)', 'Lentils (French)',
  'Split peas', 'Soybeans', 'Mung beans', 'Adzuki beans', 'Fava beans', 'Lupini beans',

  // ── Oils, Vinegars & Condiments ──────────────────────────────────────────
  'Olive oil', 'Extra virgin olive oil', 'Vegetable oil', 'Canola oil', 'Corn oil',
  'Coconut oil', 'Sesame oil', 'Toasted sesame oil', 'Mustard oil', 'Sunflower oil',
  'Avocado oil', 'Peanut oil', 'Grapeseed oil',
  'Apple cider vinegar', 'White vinegar', 'Rice vinegar', 'Balsamic vinegar',
  'Red wine vinegar', 'White wine vinegar', 'Malt vinegar', 'Sherry vinegar',
  'Soy sauce', 'Low-sodium soy sauce', 'Tamari', 'Coconut aminos',
  'Fish sauce', 'Oyster sauce', 'Hoisin sauce', 'Sriracha', 'Chili garlic sauce',
  'Sweet chili sauce', 'Black bean sauce', 'Plum sauce', 'Duck sauce',
  'Teriyaki sauce', 'Ponzu sauce', 'Mirin', 'Sake', 'Rice wine',
  'Hot sauce', 'Tabasco', 'Frank\'s RedHot',
  'Ketchup', 'Mustard', 'Dijon mustard', 'Whole grain mustard', 'Yellow mustard',
  'Mayonnaise', 'Ranch dressing', 'Caesar dressing', 'Italian dressing',
  'Blue cheese dressing', 'Thousand Island', 'Balsamic glaze',
  'Hummus', 'Baba ganoush', 'Tzatziki',
  'Tamarind paste', 'Tamarind concentrate', 'Imli (tamarind)',
  'Mango pickle (achar)', 'Lime pickle', 'Mixed pickle',
  'Coconut chutney', 'Mint chutney', 'Coriander chutney', 'Tomato chutney',
  'Salsa', 'Pico de gallo', 'Guacamole', 'Enchilada sauce', 'Mole sauce',
  'HP sauce', 'Worcestershire sauce', 'Marmite', 'Bovril', 'Branston pickle',

  // ── Canned & Jarred ──────────────────────────────────────────────────────
  'Tomato sauce', 'Marinara sauce', 'Diced tomatoes', 'Tomato paste', 'Crushed tomatoes',
  'Whole peeled tomatoes', 'Sun-dried tomatoes', 'Tomato purée',
  'Chicken broth', 'Beef broth', 'Vegetable broth', 'Bone broth',
  'Coconut milk (canned)', 'Coconut cream (canned)', 'Evaporated milk (canned)',
  'Chickpeas (canned)', 'Black beans (canned)', 'Kidney beans (canned)',
  'Pinto beans (canned)', 'Lentils (canned)', 'Corn (canned)', 'Green beans (canned)',
  'Artichoke hearts', 'Roasted red peppers', 'Olives', 'Capers',
  'Tuna (canned)', 'Sardines (canned)', 'Salmon (canned)', 'Anchovies (canned)',
  'Pumpkin puree', 'Jackfruit (canned)', 'Bamboo shoots (canned)', 'Water chestnuts (canned)',
  'Baby corn (canned)', 'Lychee (canned)', 'Mango pulp', 'Coconut water',

  // ── Spices & Masalas ────────────────────────────────────────────────────
  'Salt', 'Kosher salt', 'Sea salt', 'Himalayan pink salt', 'Black salt (kala namak)',
  'Black pepper', 'White pepper', 'Szechuan pepper', 'Red pepper flakes',
  'Cumin seeds', 'Cumin powder', 'Coriander seeds', 'Coriander powder',
  'Turmeric powder', 'Red chili powder', 'Kashmiri chili powder', 'Paprika', 'Smoked paprika',
  'Cayenne pepper', 'Chili powder (Mexican)', 'Ancho chili powder', 'Chipotle powder',
  'Garam masala', 'Curry powder', 'Sambar powder', 'Rasam powder', 'Biryani masala',
  'Chole masala', 'Pav bhaji masala', 'Kitchen king masala', 'Chaat masala',
  'Tandoori masala', 'Tikka masala paste', 'Korma paste', 'Vindaloo paste',
  'Mustard seeds (black)', 'Mustard seeds (yellow)', 'Fenugreek seeds', 'Fennel seeds',
  'Cardamom (green)', 'Cardamom (black)', 'Cloves', 'Cinnamon sticks', 'Cinnamon powder',
  'Bay leaves', 'Star anise', 'Allspice', 'Nutmeg', 'Mace', 'Saffron',
  'Asafoetida (hing)', 'Dry mango powder (amchur)', 'Kasuri methi (dried fenugreek)',
  'Curry leaves (dried)', 'Tamarind powder',
  'Italian seasoning', 'Herbes de Provence', 'Za\'atar', 'Ras el hanout',
  'Berbere', 'Dukkah', 'Sumac', 'Baharat',
  'Chinese five spice', 'White pepper (ground)', 'Szechuan peppercorns',
  'Dashi powder', 'Bonito flakes', 'Nori sheets',
  'Annatto seeds', 'Epazote (dried)', 'Mexican oregano',
  'Old Bay seasoning', 'Cajun seasoning', 'Lemon pepper',
  'Garlic powder', 'Onion powder', 'Celery salt', 'Dried basil', 'Dried thyme',
  'Dried rosemary', 'Dried oregano', 'Dried dill', 'Dried parsley', 'Dried mint',

  // ── Nuts, Seeds & Dried Fruits ───────────────────────────────────────────
  'Almonds', 'Sliced almonds', 'Cashews', 'Walnuts', 'Peanuts', 'Pistachios',
  'Pecans', 'Hazelnuts', 'Brazil nuts', 'Macadamia nuts', 'Pine nuts',
  'Sesame seeds', 'Black sesame seeds', 'Sunflower seeds', 'Pumpkin seeds',
  'Flaxseeds', 'Chia seeds', 'Hemp seeds', 'Poppy seeds', 'Nigella seeds (kalonji)',
  'Watermelon seeds',
  'Raisins', 'Golden raisins', 'Dates', 'Dried apricots', 'Dried cranberries',
  'Dried blueberries', 'Prunes', 'Dried figs', 'Dried mango', 'Dried cherries',
  'Coconut flakes', 'Desiccated coconut', 'Shredded coconut',

  // ── Sauces, Pastes & Spreads ─────────────────────────────────────────────
  'Peanut butter', 'Almond butter', 'Cashew butter', 'Sunflower seed butter',
  'Tahini', 'Nutella', 'Lotus Biscoff spread', 'Jam', 'Strawberry jam',
  'Raspberry jam', 'Marmalade', 'Jelly', 'Apple butter',
  'Miso paste (white)', 'Miso paste (red)', 'Gochujang', 'Doenjang',
  'Doubanjiang', 'XO sauce', 'Black bean paste', 'Fermented black beans',
  'Red curry paste', 'Green curry paste', 'Yellow curry paste', 'Massaman curry paste',
  'Tikka masala paste', 'Rogan josh paste',
  'Tomato ketchup', 'HP sauce', 'Worcestershire sauce', 'Marmite', 'Vegemite',

  // ── Asian & International Pantry ─────────────────────────────────────────
  'Nori (seaweed sheets)', 'Wakame (dried seaweed)', 'Kombu', 'Bonito flakes', 'Dashi',
  'Mirin', 'Sake', 'Japanese rice vinegar', 'Ponzu', 'Furikake',
  'Gochugaru (Korean chili flakes)', 'Doenjang', 'Ganjang', 'Sesame oil (Korean)',
  'Kimchi', 'Ssamjang',
  'Dried shiitake mushrooms', 'Wood ear mushrooms', 'Lily buds', 'Shaoxing wine',
  'Dark soy sauce', 'Light soy sauce', 'Pandan extract',
  'Tamarind water', 'Kecap manis', 'Shrimp paste (belacan)',
  'Annatto oil', 'Sofrito', 'Mojo sauce', 'Recao (culantro)',
  'Dried guajillo chili', 'Dried ancho chili', 'Dried pasilla chili',
  'Chipotles in adobo', 'Mexican crema', 'Cotija cheese',

  // ── South Indian Staples ─────────────────────────────────────────────────
  'Idli rice (short grain)', 'Urad dal (whole black)', 'Parboiled rice', 'Raw rice',
  'Coconut (fresh)', 'Coconut (grated frozen)', 'Curry leaves (fresh)',
  'Drumstick leaves', 'Tamarind block', 'Jaggery block', 'Palm jaggery',
  'Sesame oil (gingelly)', 'Mustard oil', 'Neem flowers (dried)',
  'Kollu (horse gram)', 'Moth beans', 'Vathal (dried vegetables)',
  'Appalam / papad', 'Rice flour (fine)', 'Idiyappam flour',
  'Coconut oil (cold-pressed)', 'Tender coconut water',

  // ── Tofu & Plant-Based ───────────────────────────────────────────────────
  'Firm tofu', 'Silken tofu', 'Soft tofu', 'Extra firm tofu',
  'Tempeh', 'Seitan', 'Plant-based ground beef', 'Plant-based sausage',
  'Plant-based burger patties', 'Plant-based chicken strips',
  'Jackfruit (young, canned)', 'Lentil patties',

  // ── Frozen ───────────────────────────────────────────────────────────────
  'Frozen peas', 'Frozen corn', 'Frozen broccoli', 'Frozen spinach', 'Frozen edamame',
  'Frozen mixed vegetables', 'Frozen berries', 'Frozen mango chunks',
  'Frozen dumplings (potstickers)', 'Frozen spring rolls', 'Frozen samosas',
  'Frozen paratha', 'Frozen roti', 'Frozen idli', 'Frozen dosa',
  'Frozen pizza', 'Frozen waffles', 'Frozen pancakes',
  'Frozen fish fillets', 'Frozen shrimp', 'Frozen salmon burgers',
  'Ice cream', 'Frozen yogurt', 'Gelato', 'Sorbet',
  'Frozen french fries', 'Frozen hash browns', 'Frozen tater tots',

  // ── Beverages ────────────────────────────────────────────────────────────
  'Orange juice', 'Apple juice', 'Cranberry juice', 'Grape juice', 'Pineapple juice',
  'Pomegranate juice', 'Tomato juice', 'V8 juice',
  'Coconut water', 'Sugarcane juice', 'Rose water', 'Kewra water',
  'Coffee (ground)', 'Whole bean coffee', 'Instant coffee', 'Espresso pods',
  'Black tea', 'Green tea', 'Chai masala', 'Tulsi tea', 'Ginger tea', 'Chamomile tea',
  'Oolong tea', 'Pu-erh tea', 'Earl Grey', 'English Breakfast tea', 'Matcha powder',
  'Horlicks', 'Boost', 'Bournvita', 'Ovaltine', 'Milo',
  'Sparkling water', 'Club soda', 'Tonic water', 'Soda', 'Diet soda',
  'Kombucha', 'Kefir (drinkable)', 'Lassi (mango)', 'Buttermilk (chilled)',
  'Sports drinks', 'Energy drinks',

  // ── Snacks ───────────────────────────────────────────────────────────────
  'Chips (potato)', 'Tortilla chips', 'Pita chips', 'Veggie chips', 'Plantain chips',
  'Popcorn', 'Microwave popcorn', 'Pretzels', 'Crackers', 'Rice cakes', 'Corn cakes',
  'Graham crackers', 'Animal crackers', 'Biscuits (UK/Indian)', 'Marie biscuits',
  'Digestive biscuits', 'Bourbon biscuits', 'Hide and Seek', 'Good Day cookies',
  'Trail mix', 'Granola bars', 'Protein bars', 'Cereal bars', 'Fruit leather',
  'Murukku', 'Chakli', 'Namkeen', 'Mixture', 'Bhujia', 'Sev', 'Mathri',
  'Khakhra', 'Thepla (ready-to-eat)', 'Rice crackers (Japanese)',
  'Seaweed snacks', 'Shrimp crackers', 'Prawn crackers',
  'Corn nuts', 'Pork rinds',

  // ── Cereal & Breakfast ───────────────────────────────────────────────────
  'Cornflakes', 'Honey Nut Cheerios', 'Frosted Flakes', 'Raisin Bran', 'Granola',
  'Muesli', 'Wheat bran', 'Shredded wheat', 'Special K', 'Fiber One',
  'Pancake mix', 'Waffle mix', 'Brownie mix', 'Cake mix', 'Muffin mix',

  // ── Household ────────────────────────────────────────────────────────────
  'Paper towels', 'Toilet paper', 'Facial tissues', 'Napkins',
  'Dish soap', 'Dish soap pods', 'Dishwasher detergent', 'Rinse aid',
  'Laundry detergent', 'Laundry pods', 'Fabric softener', 'Dryer sheets', 'Stain remover',
  'Trash bags', 'Recycling bags', 'Compost bags', 'Zip-lock bags (quart)', 'Zip-lock bags (gallon)',
  'Aluminum foil', 'Plastic wrap', 'Parchment paper', 'Wax paper', 'Butcher paper',
  'Hand soap', 'Hand sanitizer', 'Dish sponge', 'Scrub brush', 'Steel wool',
  'All-purpose cleaner', 'Bathroom cleaner', 'Toilet bowl cleaner', 'Glass cleaner',
  'Bleach', 'Disinfectant wipes', 'Mop head', 'Broom',
  'Shampoo', 'Conditioner', 'Body wash', 'Bar soap', 'Loofahs',
  'Toothpaste', 'Toothbrush', 'Mouthwash', 'Floss', 'Tongue scraper',
  'Deodorant', 'Antiperspirant', 'Sunscreen (SPF 50)', 'Moisturizer', 'Lip balm',
  'Shaving cream', 'Razors', 'Feminine hygiene products', 'Diapers', 'Baby wipes',
  'Cotton balls', 'Cotton swabs (Q-tips)', 'Bandages', 'First aid kit',
  'Vitamin C', 'Multivitamins', 'Fish oil', 'Probiotics', 'Melatonin',
  'Ibuprofen', 'Acetaminophen', 'Antacids', 'Allergy medicine',
  'Batteries (AA)', 'Batteries (AAA)', 'Light bulbs', 'Candles', 'Matches',
  'Zippered bags (small)', 'Command strips', 'Duct tape', 'Super glue',
  'Pet food (dog)', 'Pet food (cat)', 'Cat litter', 'Pet treats', 'Flea treatment',
];

export const DEFAULT_GROCERY_STORES = [
  // US General
  'Walmart', 'Target', 'Costco', 'Kroger', 'Safeway', 'Whole Foods', 'Trader Joe\'s',
  'Aldi', 'HEB', 'Publix', 'Meijer', 'Sam\'s Club', 'Sprouts', 'Wegmans',
  'Food Lion', 'Giant', 'Stop & Shop', 'Winn-Dixie', 'Smart & Final',
  'Price Chopper', 'Hannaford', 'Stater Bros', 'WinCo Foods', 'Grocery Outlet',
  'Lucky Supermarkets', 'Ralphs', 'Vons', 'Fry\'s', 'Smith\'s', 'Dillons',
  // Indian & South Asian
  'Patel Brothers', 'India Bazaar', 'Apna Bazar', 'Subzi Mandi', 'Swagat Indian Grocery',
  'Suvidha Indian Grocery', 'Spice Route', 'Desi Brothers', 'Gandhi Bazar', 'Bharat Bazaar',
  // Asian & International
  'Lotte Market', 'H Mart', '99 Ranch Market', 'Seafood City', 'Mitsuwa',
  'Nijiya', 'Kim\'s Asian Market', 'Super H Mart', 'Han Yang Market',
  'Zion Market', 'Uwajimaya', 'Lion Supermarket', 'Ranch 99',
  // UK
  'Tesco', 'Tesco Express', 'Sainsbury\'s', 'Sainsbury\'s Local', 'Asda', 'Morrisons',
  'Waitrose', 'M&S Food', 'Lidl', 'Aldi (UK)', 'Iceland', 'Spar', 'Co-op', 'Budgens',
  // Online / Delivery
  'Amazon Fresh', 'Instacart', 'DoorDash', 'Walmart Grocery Pickup',
  'FreshDirect', 'Thrive Market', 'Shipt', 'Gopuff',
];
