import { StyleSheet } from 'react-native';

export const makeStyles = (colors: any, isDark: boolean, width: number) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.background },

    appBar: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
      paddingHorizontal: 16, paddingTop: 6, paddingBottom: 10,
      backgroundColor: colors.background,
    },
    petleyLogoBox: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center', marginRight: 4 },
    greetWrap: { flex: 1, justifyContent: 'center', paddingRight: 8 },
    greetWord: { fontSize: 14, color: '#ff69b4', fontWeight: '700', fontStyle: 'italic' },
    greetName: { fontSize: 21, fontWeight: '800', color: colors.textPrimary, letterSpacing: -0.3, marginTop: 1 },
    appBarRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    bellBtn: {
      width: 40, height: 40, borderRadius: 13,
      backgroundColor: isDark ? colors.card : 'rgba(255,255,255,0.7)',
      borderWidth: 1, borderColor: colors.border,
      alignItems: 'center', justifyContent: 'center', position: 'relative',
      shadowColor: colors.primary, shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 1 }, shadowRadius: 4,
    },

    switcherScroll: { backgroundColor: 'transparent' },
    switcherContent: { paddingHorizontal: 18, paddingTop: 6, paddingBottom: 14, gap: 16, flexDirection: 'row' },
    petAvatarCol: { alignItems: 'center', gap: 6, width: 72 },
    petAvatarRing: { width: 68, height: 68, borderRadius: 34, borderWidth: 2.5, borderColor: 'transparent', alignItems: 'center', justifyContent: 'center' },
    petAvatarLg: { width: 60, height: 60, borderRadius: 30, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderWidth: 2, borderColor: isDark ? colors.surface : '#fff' },
    petAvatarLgEmoji: { fontSize: 28 },
    petAvatarLgPhoto: { width: 60, height: 60, borderRadius: 30 },
    petAvatarName: { fontSize: 14, maxWidth: 72 },
    petAvatarAddRing: { width: 60, height: 60, borderRadius: 30, borderWidth: 1.5, borderStyle: 'dashed', borderColor: colors.borderMed, alignItems: 'center', justifyContent: 'center', marginTop: 4 },

    petStrip: { marginHorizontal: 16, marginTop: 2, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 14, paddingVertical: 10 },
    petStripRing: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
    petStripAvatar: { width: 44, height: 44, borderRadius: 22 },
    petStripName: { fontSize: 16, fontWeight: '800', letterSpacing: -0.3, flexShrink: 1 },
    petStripBreed: { fontSize: 14, marginTop: 1 },

    widgetGrid: { marginHorizontal: 16, marginBottom: 12, flexDirection: 'row', gap: 8, alignItems: 'stretch' },
    widgetColLeft: { flex: 1 },
    widgetColRight: { flex: 1, gap: 6 },
    widgetTileTall: { flex: 1, borderRadius: 16, borderWidth: 1, padding: Math.min(9, width * 0.023), minHeight: Math.min(186, width * 0.46) },
    widgetTile: { borderRadius: 12, borderWidth: 1, padding: Math.min(9, width * 0.023), minHeight: Math.min(80, width * 0.195) },
    widgetLabel: { fontSize: Math.min(8.5, width * 0.021), fontWeight: '800', letterSpacing: 0.8 },
    widgetBigNum: { fontSize: Math.min(30, width * 0.074), fontWeight: '900', lineHeight: Math.min(34, width * 0.083), letterSpacing: -2, marginTop: 2 },
    widgetSub: { fontSize: Math.min(9.5, width * 0.023), fontWeight: '500', marginTop: 1 },
    widgetAvatar: { width: 30, height: 30, borderRadius: 15, borderWidth: 2 },
    widgetStreakPill: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 7, alignSelf: 'flex-start' },
    widgetStreakText: { fontSize: Math.min(10.5, width * 0.025), fontWeight: '700' },
    widgetScanBadge: { flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 5, paddingVertical: 2, borderRadius: 6 },
    widgetMoodLabel: { fontSize: Math.min(12, width * 0.029), fontWeight: '700' },
    widgetApptName: { fontSize: Math.min(14, width * 0.034), fontWeight: '800', marginTop: 3, letterSpacing: -0.3 },
    widgetActivityStrip: { marginHorizontal: 16, marginBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 12, paddingVertical: 8 },
    widgetActivityText: { fontSize: 14, flex: 1 },

    sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 9 },
    sectionHeaderLabel: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },
    sectionHeaderLink: { fontSize: 14, fontWeight: '600', color: colors.primaryText ?? colors.primary },

    splitCard: { marginHorizontal: 16, marginBottom: 18, height: 162, borderRadius: 18, overflow: 'hidden', flexDirection: 'row', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, shadowColor: colors.primary, shadowOpacity: 0.07, shadowOffset: { width: 0, height: 3 }, shadowRadius: 12, elevation: 2 },
    splitPhotoWrap: { flex: 1 },
    splitPhotoInner: { flex: 1, margin: 9, borderRadius: 13, overflow: 'hidden' },
    splitPhoto: { width: '100%', height: '100%' },
    splitNoPhotoCenter: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center' },
    splitNoPhotoEmoji: { fontSize: 120 },
    splitPhotoOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, paddingHorizontal: 9, paddingTop: 28, paddingBottom: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    splitPetName: { fontSize: 14, fontWeight: '800', color: '#fff' },
    splitPetMoodEmoji: { fontSize: 18 },
    splitDivider: { width: StyleSheet.hairlineWidth, backgroundColor: colors.border },
    splitMoodWrap: { flex: 1, paddingHorizontal: 11, paddingTop: 11, paddingBottom: 11, justifyContent: 'space-between' },
    splitMoodHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    splitMoodTitle: { fontSize: 14, fontWeight: '800', color: colors.textPrimary, letterSpacing: -0.2 },
    splitStreakBadge: { backgroundColor: colors.warning + '22', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 7 },
    splitStreakText: { fontSize: 14, fontWeight: '700', color: colors.warning },
    splitMoodGrid: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' },
    splitMoodCol: { flex: 1, alignItems: 'center', gap: 4 },
    splitMoodEmoji: { fontSize: 15 },
    splitMoodDot: { width: '80%', height: 3, borderRadius: 2 },
    splitMoodDay: { fontSize: 14, color: colors.textSecondary, fontWeight: '500' },
    splitLoggedRow: { flexDirection: 'row', alignItems: 'baseline', gap: 2 },
    splitLoggedNum: { fontSize: 22, fontWeight: '800', color: colors.primaryText ?? colors.primary, lineHeight: 24 },
    splitLoggedSub: { fontSize: 14, color: colors.textSecondary, fontWeight: '500', lineHeight: 13 },

    summaryRow: { flexDirection: 'row', gap: 10, marginHorizontal: 16, marginBottom: 12 },
    summaryTile: { flex: 1, backgroundColor: colors.card, borderRadius: 16, padding: 13, borderWidth: 1, borderColor: colors.border, shadowColor: colors.primary, shadowOpacity: 0.05, shadowOffset: { width: 0, height: 2 }, shadowRadius: 8, elevation: 2 },
    summaryTileHead: { flexDirection: 'row', alignItems: 'center', gap: 5, marginBottom: 8 },
    summaryTileLabel: { fontSize: 14, fontWeight: '600', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.3 },
    summaryTileValue: { fontSize: 22, fontWeight: '800', color: colors.textPrimary, lineHeight: 26 },
    summaryTileDivider: { fontSize: 15, fontWeight: '500', color: colors.textSecondary },
    summaryTileSub: { fontSize: 14, color: colors.textSecondary, marginTop: 2 },

    sectionTitle: { fontSize: 13, fontWeight: '700', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.9, paddingHorizontal: 16, marginTop: 4, marginBottom: 10 },

    actionsRow: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 16, marginBottom: 20 },
    actionCol: { flex: 1, alignItems: 'center', gap: 7 },
    actionIconWrap: { width: 62, height: 62, borderRadius: 20, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' },
    actionLabel: { fontSize: 14, fontWeight: '600', color: colors.textSecondary },

    actionsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingHorizontal: 16, marginBottom: 12 },
    actionGridCard: { width: (width - 32 - 8) / 2, borderRadius: 14, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 9, shadowColor: '#000', shadowOpacity: 0.04, shadowOffset: { width: 0, height: 1 }, shadowRadius: 4, elevation: 2 },
    actionGridIcon: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center' },
    actionGridLabel: { fontSize: 15, fontWeight: '700', flex: 1 },

    discoverWrap: { marginBottom: 12, paddingHorizontal: 16 },
    discoverSub: { fontSize: 14, color: colors.textSecondary, marginTop: 1 },
    discoverLoading: { height: 120, alignItems: 'center', justifyContent: 'center' },
    discoverEmpty: { height: 120, alignItems: 'center', justifyContent: 'center', gap: 4 },
    discoverEmptyEmoji: { fontSize: 32, lineHeight: 38 },
    discoverEmptyText: { fontSize: 15, fontWeight: '600', color: colors.textSecondary, textAlign: 'center', marginTop: 4 },
    discoverEmptySub: { fontSize: 14, color: colors.textSecondary, textAlign: 'center' },
    chipRow: { gap: 8, paddingVertical: 11, paddingRight: 8 },
    chip: { paddingHorizontal: 13, paddingVertical: 6, borderRadius: 20, borderWidth: 1, flexDirection: 'row', alignItems: 'center' },
    chipText: { fontSize: 14, fontWeight: '600' },
    cardRow: { gap: 12, paddingRight: 8, paddingBottom: 2 },
    partnerCard: { width: 158, backgroundColor: colors.card, borderRadius: 16, borderWidth: 1, borderColor: colors.border, overflow: 'hidden' },
    partnerBanner: { height: 90, alignItems: 'center', justifyContent: 'center', position: 'relative' },
    sponsoredTag: { position: 'absolute', top: 8, left: 8, backgroundColor: 'rgba(255,255,255,0.93)', paddingHorizontal: 7, paddingVertical: 2.5, borderRadius: 6 },
    sponsoredTagText: { fontSize: 14, fontWeight: '700', color: '#52525B', letterSpacing: 0.2 },
    openTag: { position: 'absolute', top: 8, right: 8, backgroundColor: 'rgba(255,255,255,0.93)', paddingHorizontal: 7, paddingVertical: 2.5, borderRadius: 6 },
    openTagText: { fontSize: 14, fontWeight: '700', color: '#1E7B0E' },
    ratingTag: { position: 'absolute', top: 8, right: 8, backgroundColor: '#E8A320', paddingHorizontal: 7, paddingVertical: 3, borderRadius: 7 },
    ratingTagText: { fontSize: 14, fontWeight: '700', color: '#fff' },
    partnerBody: { padding: 11 },
    partnerName: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },
    partnerSub: { fontSize: 14, color: colors.textSecondary, marginTop: 2 },
    partnerMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 7, flexWrap: 'wrap' },
    partnerRating: { fontSize: 14, color: colors.warning, fontWeight: '600' },
    partnerMeta: { fontSize: 14, color: colors.textSecondary },
    partnerPrice: { fontSize: 14, color: colors.success, fontWeight: '600' },
    partnerCtaRow: { flexDirection: 'row', gap: 6, marginTop: 9 },
    partnerCta: { paddingVertical: 6, borderRadius: 9, alignItems: 'center', paddingHorizontal: 8 },
    partnerCtaText: { fontSize: 14, fontWeight: '700' },
    partnerCtaIcon: { width: 32, height: 32, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },

    pickWrap: { marginHorizontal: 16, marginBottom: 12 },
    pickCard: { marginTop: 9, backgroundColor: colors.card, borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12, position: 'relative' },
    adTag: { position: 'absolute', top: 10, right: 12, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 6, paddingVertical: 1, borderRadius: 5 },
    adTagText: { fontSize: 14, fontWeight: '600', color: colors.textSecondary },
    pickThumb: { width: 60, height: 60, borderRadius: 12, flexShrink: 0, backgroundColor: colors.primaryLight, alignItems: 'center', justifyContent: 'center' },
    pickThumbEmoji: { fontSize: 30, lineHeight: 36 },
    pickInfo: { flex: 1, minWidth: 0 },
    pickName: { fontSize: 15, fontWeight: '700', color: colors.textPrimary, paddingRight: 28 },
    pickReason: { fontSize: 14, color: colors.textSecondary, marginTop: 2 },
    pickPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8 },
    pickPrice: { fontSize: 15, fontWeight: '700', color: colors.textPrimary },
    pickStrike: { fontSize: 14, color: colors.textSecondary, textDecorationLine: 'line-through' },
    pickCta: { marginLeft: 'auto', paddingHorizontal: 14, paddingVertical: 6, borderRadius: 9 },
    pickCtaText: { fontSize: 14, fontWeight: '700', color: '#fff' },
    whyRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 7, paddingHorizontal: 4 },
    whyText: { fontSize: 14, color: colors.textSecondary, flex: 1 },

    yearCard: { marginHorizontal: 16, borderRadius: 18, padding: 14, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 13, overflow: 'hidden', borderWidth: 1, borderColor: colors.border },
    yearIcon: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
    yearMid: { flex: 1, minWidth: 0 },
    yearBadge: { fontSize: 14, fontWeight: '700', letterSpacing: 1, marginBottom: 2, textTransform: 'uppercase', color: colors.accent },
    yearTitle: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2, color: isDark ? '#fff' : colors.textPrimary },
    yearBarBg: { height: 5, borderRadius: 3, overflow: 'hidden', backgroundColor: isDark ? 'rgba(255,255,255,0.10)' : 'rgba(124,92,191,0.15)' },
    yearBarFill: { height: 5, borderRadius: 3 },
    yearCta: { width: 34, height: 34, borderRadius: 11, flexShrink: 0, alignItems: 'center', justifyContent: 'center', backgroundColor: isDark ? 'rgba(255,255,255,0.14)' : colors.primary, borderWidth: isDark ? 1.5 : 0, borderColor: 'rgba(255,255,255,0.25)' },
    yearCtaText: { fontSize: 15, fontWeight: '700', color: '#fff' },

    emptyWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
    emptyEmoji: { fontSize: 72, marginBottom: 20 },
    emptyTitle: { fontSize: 24, fontWeight: '700', color: colors.textPrimary, marginBottom: 8, letterSpacing: -0.5 },
    emptySub: { fontSize: 14, color: colors.textSecondary, marginBottom: 24 },
    addBtn: { backgroundColor: colors.primary, paddingHorizontal: 32, paddingVertical: 14, borderRadius: 14 },
    addBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  });
