import { StyleSheet } from 'react-native';

// Counter-propose sheet
export const cps = StyleSheet.create({
  label:        { fontSize: 14, fontWeight: '600', marginBottom: 6, marginTop: 12 },
  input:        { borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, height: 44, fontSize: 14 },
  dateBtn:      { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 11, minWidth: 90 },
  dateBtnText:  { fontSize: 14, flex: 1 },
  pickerSheet:  { borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: 34 },
  pickerHead:   { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 14 },
  footer:       { flexDirection: 'row', gap: 10, paddingTop: 12, borderTopWidth: StyleSheet.hairlineWidth },
  cancelBtn:    { flex: 1, height: 50, borderWidth: 1, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  cancelText:   { fontSize: 15, fontWeight: '600' },
  saveBtn:      { flex: 2, height: 50, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  saveBtnText:  { color: '#fff', fontSize: 15, fontWeight: '700' },
});

// Screen / header / tab bar
export const sc = StyleSheet.create({
  header:   { flexDirection: 'row', alignItems: 'center', gap: 10,
              paddingHorizontal: 16, paddingTop: 6, paddingBottom: 12, borderBottomWidth: StyleSheet.hairlineWidth },
  title:    { fontSize: 22, fontWeight: '900', letterSpacing: -0.5 },
  sub:      { fontSize: 14, marginTop: 1, opacity: 0.6 },
  addBtn:   { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  tabRow:   { flexDirection: 'row', paddingHorizontal: 12, paddingVertical: 6, gap: 4 },
  tabBtn:   { flex: 1, alignItems: 'center', paddingVertical: 8, borderRadius: 22 },
  tabLabel: { fontSize: 14, fontWeight: '700' },
  floatingBtn: { position: 'absolute', right: 20, width: 52, height: 52, borderRadius: 26,
                 alignItems: 'center', justifyContent: 'center',
                 shadowColor: '#000', shadowOpacity: 0.28, shadowRadius: 12, shadowOffset: { width: 0, height: 6 },
                 elevation: 8 },
  floatingBtnText: { fontSize: 14, fontWeight: '800', color: '#fff' },
});

// Feed tab styles
export const fd = StyleSheet.create({
  filterWrap:      { borderBottomWidth: StyleSheet.hairlineWidth },
  statBar:         { flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 8 },
  statItem:        { flex: 1, alignItems: 'center', gap: 1 },
  statNum:         { fontSize: 16, fontWeight: '800', letterSpacing: -0.5 },
  statLabel:       { fontSize: 14, fontWeight: '500', letterSpacing: 0.1 },
  statDivider:     { width: StyleSheet.hairlineWidth, height: 28 },
  feedTabBar:      { borderBottomWidth: StyleSheet.hairlineWidth, flexShrink: 0 },
  feedTabBtn:      { height: 54, flex: 1, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  feedTabTxt:      { fontSize: 18, fontWeight: '700', letterSpacing: -0.3 },
  feedTabUnderline:{ position: 'absolute', bottom: 0, left: 18, right: 18, height: 2.5, borderRadius: 2 },
  feedTabBadge:    { paddingHorizontal: 5, paddingVertical: 1, borderRadius: 8, minWidth: 17, alignItems: 'center' },
  feedTabBadgeTxt: { fontSize: 14, fontWeight: '800' },
  petChip:         { flexDirection: 'row', alignItems: 'center', gap: 8, paddingRight: 14, paddingLeft: 6,
                     paddingVertical: 6, borderRadius: 24, borderWidth: 1.5,
                     shadowOpacity: 0.18, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  petChipAvatar:   { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  petChipImg:      { width: 32, height: 32, borderRadius: 16 },
  petChipName:     { fontSize: 14, fontWeight: '700' },
  activeIndicator: { position: 'absolute', top: 5, right: 5, width: 6, height: 6,
                     borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.9)' },
  chip:            { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, paddingVertical: 7,
                     borderRadius: 20, borderWidth: 1 },
  chipText:        { fontSize: 14, fontWeight: '700' },
  createBar:       { flexDirection: 'row', alignItems: 'center', gap: 10, marginHorizontal: 16,
                     marginTop: 12, marginBottom: 4, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 20,
                     borderWidth: StyleSheet.hairlineWidth,
                     shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  petPickerBadge:  { position: 'absolute', bottom: -1, right: -1, width: 16, height: 16, borderRadius: 8,
                     alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#fff' },
  createPill:      { flex: 1, height: 38, borderRadius: 19, paddingHorizontal: 14, justifyContent: 'center', borderWidth: 1 },
  photoIcon:       { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  searchBar:       { flexDirection: 'row', alignItems: 'center', gap: 10, marginHorizontal: 16, marginTop: 12,
                     paddingHorizontal: 16, paddingVertical: 11, borderRadius: 18, borderWidth: 1.5 },
  searchInput:     { flex: 1, fontSize: 16, fontWeight: '500' },
  resultCount:     { fontSize: 14, fontWeight: '600', marginHorizontal: 16, marginTop: 8, marginBottom: 10 },
  empty:           { alignItems: 'center', paddingTop: 56, paddingHorizontal: 32, gap: 10 },
  emptyTitle:      { fontSize: 17, fontWeight: '800', marginTop: 8, letterSpacing: -0.3 },
  emptySub:        { fontSize: 14, textAlign: 'center', lineHeight: 20, opacity: 0.7 },
  emptyBtn:        { marginTop: 14, paddingHorizontal: 32, paddingVertical: 13, borderRadius: 24 },
});

// Nearby tab styles
export const nb = StyleSheet.create({
  emptyNearby:      { marginHorizontal: 16, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth,
                      padding: 20, alignItems: 'center', gap: 8, marginBottom: 8 },
  emptyNearbyTitle: { fontSize: 14, fontWeight: '700', textAlign: 'center', letterSpacing: -0.2 },
  emptyNearbySub:   { fontSize: 14, textAlign: 'center', opacity: 0.55, lineHeight: 18 },
  centerBlock:    { alignItems: 'center', paddingVertical: 48, paddingHorizontal: 32, gap: 12 },
  bigIcon:        { width: 72, height: 72, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  bigTitle:       { fontSize: 17, fontWeight: '800', textAlign: 'center', letterSpacing: -0.3 },
  bigSub:         { fontSize: 14, textAlign: 'center', lineHeight: 20, opacity: 0.7 },
  primaryBtn:     { paddingHorizontal: 28, paddingVertical: 12, borderRadius: 22, marginTop: 4 },
  primaryBtnText: { fontSize: 14, fontWeight: '800', color: '#fff' },
  locBanner:      { flexDirection: 'row', alignItems: 'center', gap: 6,
                    marginHorizontal: 16, marginTop: 8, marginBottom: 2,
                    paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, borderWidth: 1 },
  locText:        { fontSize: 14, flex: 1 },
  searchWrap:     { flexDirection: 'row', alignItems: 'center', gap: 8, height: 42,
                    borderWidth: 1, borderRadius: 14, paddingHorizontal: 14,
                    marginHorizontal: 16, marginTop: 8, marginBottom: 4 },
  searchInput:    { flex: 1, fontSize: 14 },
  sectionHeader:  { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
                    paddingHorizontal: 16, marginTop: 20, marginBottom: 12 },
  sectionTitle:   { fontSize: 15, fontWeight: '800', letterSpacing: -0.3 },
  sectionSub:     { fontSize: 14, opacity: 0.6 },
  showAllBtn:     { flexDirection: 'row', alignItems: 'center', gap: 4,
                    paddingHorizontal: 12, paddingVertical: 7, borderRadius: 16 },
  showAllText:    { fontSize: 14, fontWeight: '800' },
  createEventBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 18,
                    paddingHorizontal: 14, paddingVertical: 7 },
  requestCard:    { flexDirection: 'column', gap: 10,
                    marginHorizontal: 16, marginBottom: 10,
                    borderRadius: 16, borderWidth: StyleSheet.hairlineWidth,
                    padding: 14 },
  requestEmoji:   { width: 50, height: 50, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  requestName:    { fontSize: 14.5, fontWeight: '800', letterSpacing: -0.2 },
  requestMeta:    { fontSize: 14, fontWeight: '600' },
  requestTime:    { fontSize: 14, marginTop: 2, opacity: 0.6 },
  acceptBtn:      { borderRadius: 20, paddingHorizontal: 18, paddingVertical: 9, flex: 2, alignItems: 'center' },
  declineBtn:     { borderRadius: 20, paddingHorizontal: 14, paddingVertical: 9, borderWidth: 1.5, flex: 1, alignItems: 'center' },
});

// Family tab styles
export const fm = StyleSheet.create({
  banner:      { marginHorizontal: 16, borderRadius: 18, borderWidth: 1, padding: 16,
                 flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 20 },
  bannerIcon:  { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  bannerTitle: { fontSize: 15, fontWeight: '800', letterSpacing: -0.2 },
  bannerSub:   { fontSize: 14, marginTop: 3, opacity: 0.7 },
  inviteBtn:   { flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 20,
                 paddingHorizontal: 14, paddingVertical: 8 },
  sectionLabel:{ fontSize: 14, fontWeight: '800', letterSpacing: 1.2, marginHorizontal: 16, marginBottom: 8 },
  membersCard: { marginHorizontal: 16, borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, overflow: 'hidden',
                 shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 2 },
  memberRow:   { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14 },
  memberName:  { fontSize: 14.5, fontWeight: '700', letterSpacing: -0.2 },
  memberSince: { fontSize: 14, marginTop: 2, opacity: 0.6 },
  roleBadge:   { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 10,
                 borderWidth: 1, paddingHorizontal: 9, paddingVertical: 4 },
  roleText:    { fontSize: 14, fontWeight: '700' },
  permCard:     { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginHorizontal: 16,
                  marginBottom: 10, padding: 14, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth },
  permIconWrap: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  permRole:     { fontSize: 14, fontWeight: '800', marginBottom: 8, letterSpacing: -0.2 },
  permGrid:     { flexDirection: 'row', flexWrap: 'wrap', columnGap: 0, rowGap: 6 },
  permItem:     { flexDirection: 'row', alignItems: 'center', gap: 6, width: '50%' },
  permLabel:    { fontSize: 14, flex: 1 },
});

// Edit post photo styles
export const ep = StyleSheet.create({
  photoBtn:    { flexDirection: 'row', alignItems: 'center', gap: 5, borderWidth: 1, borderRadius: 10,
                 paddingHorizontal: 12, paddingVertical: 7, justifyContent: 'center' },
  photoBtnTxt: { fontSize: 14, fontWeight: '600' },
  removedBox:  { alignItems: 'center', borderWidth: 1, borderRadius: 12, borderStyle: 'dashed', paddingVertical: 18 },
  addPhotoBtn: { alignItems: 'center', borderWidth: 1.5, borderRadius: 12, borderStyle: 'dashed', paddingVertical: 18 },
});

// Modals / dialogs
export const md = StyleSheet.create({
  footer:      { flexDirection: 'row', gap: 10, paddingTop: 12,
                 borderTopWidth: StyleSheet.hairlineWidth },
  sub:       { fontSize: 15, marginBottom: 14, opacity: 0.7 },
  label:     { fontSize: 14, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 7, marginTop: 16 },
  input:     { height: 48, borderWidth: 1.5, borderRadius: 12, paddingHorizontal: 14, fontSize: 15 },
  typeChip:  { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 18, borderWidth: 1.5 },
  roleRow:   { flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1.5, borderRadius: 14, padding: 12, marginBottom: 8 },
  roleIcon:  { width: 36, height: 36, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  roleIcon2: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  radio:     { width: 20, height: 20, borderRadius: 10, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  radioDot:  { width: 8, height: 8, borderRadius: 4, backgroundColor: '#fff' },
  cancelBtn:   { flex: 1, height: 52, borderWidth: 1.5, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  sendBtn:     { flex: 1, height: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  pickerBtn:   { flexDirection: 'row', alignItems: 'center', gap: 8, height: 46, borderWidth: 1.5,
                 borderRadius: 12, paddingHorizontal: 14 },
  pickerInline:{ borderRadius: 16, borderWidth: 1, marginTop: 8, overflow: 'hidden', paddingBottom: 4 },
  pickerDone:  { marginHorizontal: 12, marginBottom: 8, height: 40, borderRadius: 10,
                 alignItems: 'center', justifyContent: 'center' },
});

// Playdates tab styles
export const pd = StyleSheet.create({
  card:       { borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, padding: 14, marginBottom: 10 },
  ava:        { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  declineBtn: { paddingVertical: 11, borderRadius: 12, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' },
  chatBtn:    { paddingVertical: 11, borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 },
  btn:        { paddingVertical: 12, paddingHorizontal: 24, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 8 },
});
